import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import TabsComponents from '@/components/TabsComponents'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>codedamn assignemnt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.homeMainParent}>
        <br />
        <br />
        <br />
        <p className={styles.Note}> Note :- If you do not want to fill the entire form such as name, work exp, bio, education, etc. You can directly go to the <Link className=' text-yellow-800 underline' href={"/user"}>user </Link> page and see the user profile page with hard coded data.
          However if you fill the entire form and visit the last tab "Portfolio" and click on save changes button then you will be redirected to the <Link className=' text-yellow-800 underline' href={"/user"}>user </Link> with all the data you had entered in the form.
        </p>
        <TabsComponents />
      </div>
    </>
  )
}
